# automation:

- alias: "Turn Garage Lights on on Motion"
  trigger: 
   platform: state
   entity_id: sensor.garage_motion_sensor_alarm_level
   from: '0'
   to: '255'
  action:
    service: switch.turn_on
    entity_id: switch.garage_lights_switch
#    service: google_say
#    data:
#      entity_id: media_player.living_room_home
#      message: "motion detected in the garage"

- alias: "Turn Garage Lights off on no Motion"
  trigger: 
    platform: state
    entity_id: sensor.garage_motion_sensor_alarm_level
    to: '0'
    for:
      minutes: 6
  action:
    service: switch.turn_off
    entity_id: switch.garage_lights_switch
